# Site settings
title: Cesar Garcia Santana
description: A website with some goodies.

# GitHub important stuff
email: cesargs@berkeley.edu
baseurl: / # the subpath of your site, e.g. /blog
url: https://cesarg-s.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  CesarG-S

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

plugins:
  - jekyll-feed


